# .github/workflows/ci.yml

name: Python Sum Addition

# Controls when the action will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that will run
jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3


      - name: Download Python artifact
        uses: actions/download-artifact@v3
        with:
          name: python-artifact
          path: ./python

      - name: Unpack Python artifact
        run: |
          mkdir -p ./python
          tar -xzf ./python/python-package.tar.gz -C ./python

      - name: Install Python
        run: |
          cd ./python/dist
          pip install *.whl

      - name: Verify Python installation
        run: python --version

